import { asset } from './company'

export interface Project {
  id: string
  title: string
  location: string
  year: number
  type: 'replacement' | 'storm' | 'commercial' | 'insurance'
  material: string
  image: string
  imageAlt: string
  description: string
  sqft: number
  duration: string
}

const img = (name: string) => asset(`/images/${name}.jpg`)

export const PROJECTS: Project[] = [
  {
    id: 'chatham-replacement',
    title: 'Full Shingle Replacement',
    location: 'Chatham',
    year: 2024,
    type: 'replacement',
    material: 'GAF Timberline HDZ, Charcoal',
    image: img('proj-full-replacement'),
    imageAlt: 'Two roofers in safety harnesses working on a new charcoal shingle roof',
    description: 'Tear-off of 22-year-old 3-tab shingles. New ice & water shield at the eaves and valleys, two sheets of decking replaced, and a new ridge vent.',
    sqft: 2200,
    duration: '1 day',
  },
  {
    id: 'taylorville-hail',
    title: 'Hail Damage Re-Roof',
    location: 'Taylorville',
    year: 2024,
    type: 'storm',
    material: 'GAF Timberline AS II, Weathered Wood',
    image: img('proj-hail-repair'),
    imageAlt: 'Roofers in harnesses fastening new shingles after a hailstorm',
    description: 'April 2024 hail bruised shingles on every plane. Claim filed with our drone report and approved in 18 days. The homeowner paid their deductible.',
    sqft: 1850,
    duration: '1 day',
  },
  {
    id: 'springfield-tearoff',
    title: 'Two-Layer Tear-Off',
    location: 'Springfield',
    year: 2023,
    type: 'replacement',
    material: 'GAF Timberline HDZ, Hickory',
    image: img('proj-tear-off'),
    imageAlt: 'Roofer tearing old shingles off a house roof with a shovel',
    description: 'Original 1987 roof with a second layer nailed over it. Both layers came off, and 340 sq ft of soft OSB decking was replaced before the new roof went on.',
    sqft: 2650,
    duration: '2 days',
  },
  {
    id: 'chatham-wind',
    title: 'Wind Damage: Tarp to Repair',
    location: 'Chatham',
    year: 2023,
    type: 'storm',
    material: 'GAF Timberline AS II, Barkwood',
    image: img('proj-wind-tarp'),
    imageAlt: 'Worker in a hard hat nailing down an emergency tarp on a shingle roof',
    description: 'August 2023 straight-line winds lifted the ridge cap and three field sections. Tarped the same evening, permanent repair finished two days later.',
    sqft: 1100,
    duration: '1 day',
  },
  {
    id: 'springfield-commercial',
    title: 'Commercial TPO Flat Roof',
    location: 'Springfield',
    year: 2024,
    type: 'commercial',
    material: '60-mil TPO, white',
    image: img('proj-commercial-tpo'),
    imageAlt: 'White single-ply membrane flat roof with rooftop HVAC units',
    description: 'Failing EPDM membrane with six active leaks. Replaced with 60-mil TPO over tapered insulation so water drains instead of ponding.',
    sqft: 8400,
    duration: '4 days',
  },
  {
    id: 'sherman-farm',
    title: 'Farm Buildings After Storm',
    location: 'Sherman',
    year: 2022,
    type: 'insurance',
    material: 'GAF Timberline HDZ, Slate + metal outbuilding panels',
    image: img('proj-farm-storm'),
    imageAlt: 'Storm-damaged farm buildings and grain bins behind a cornfield',
    description: 'July 2022 storms damaged the house, a detached garage, and a pole barn. All three went on a single claim, so the owners paid one deductible.',
    sqft: 4800,
    duration: '3 days',
  },
  {
    id: 'rochester-builder-grade',
    title: 'Builder-Grade Upgrade',
    location: 'Rochester',
    year: 2023,
    type: 'replacement',
    material: 'GAF Timberline HDZ, Fox Hollow Gray',
    image: img('proj-new-construction'),
    imageAlt: 'Row of newer homes with architectural shingle roofs',
    description: 'Ten-year-old builder-grade shingles replaced ahead of resale. The drone inspection also found two flashing details the builder had skipped.',
    sqft: 2100,
    duration: '1 day',
  },
  {
    id: 'riverton-ice-dam',
    title: 'Ice Dam Remediation',
    location: 'Riverton',
    year: 2023,
    type: 'replacement',
    material: 'GAF Timberline AS II, Driftwood',
    image: img('proj-ice-dam'),
    imageAlt: 'Icicles hanging from the shingled eave of a dark-sided house',
    description: 'Ice dams were pushing water into the walls every winter. Re-roofed with 6 feet of ice & water shield at the eaves and added intake ventilation.',
    sqft: 1750,
    duration: '1 day',
  },
  {
    id: 'auburn-cedar',
    title: 'Cedar Shake Replacement',
    location: 'Auburn',
    year: 2023,
    type: 'replacement',
    material: 'GAF Timberline HDZ, Pewter Gray',
    image: img('proj-cedar-shake'),
    imageAlt: 'Weathered, split cedar shake roofing',
    description: '1940s home with its original cedar shake under a later 3-tab layer. Careful two-layer tear-off that kept the original roof boards where they were sound.',
    sqft: 1950,
    duration: '2 days',
  },
  {
    id: 'springfield-retail',
    title: 'Retail Building: Modified Bitumen',
    location: 'Springfield',
    year: 2024,
    type: 'commercial',
    material: 'Two-ply SBS modified bitumen',
    image: img('proj-modbit'),
    imageAlt: 'Roofer unrolling a new membrane on a flat commercial roof',
    description: 'Four-tenant retail building. The roof was replaced over two weekends in sections, so every store stayed open.',
    sqft: 12000,
    duration: '2 weekends',
  },
  {
    id: 'springfield-insurance',
    title: 'Insurance-Funded Replacement',
    location: 'Springfield',
    year: 2024,
    type: 'insurance',
    material: 'GAF Timberline HDZ, Mission Brown',
    image: img('proj-insurance-replacement'),
    imageAlt: 'Roofer standing on a partially torn-off roof of a brick house',
    description: 'Full replacement after the April 2024 hail. The homeowner paid a $1,250 deductible; the insurer covered the remaining $13,550 of the approved claim.',
    sqft: 2300,
    duration: '1 day',
  },
  {
    id: 'petersburg-drone',
    title: 'Drone-Found Hidden Damage',
    location: 'Petersburg',
    year: 2024,
    type: 'storm',
    material: 'GAF Timberline AS II, Charcoal',
    image: img('proj-drone-find'),
    imageAlt: 'Aerial drone photo looking down on a house roof',
    description: 'The homeowner asked for an inspection after neighbors filed claims. Our drone found wind-creased shingles on the back slopes that could not be seen from the ground. Claim approved.',
    sqft: 2050,
    duration: '1 day',
  },
]
